Ocultar Horário Obrigatório
cpejr/frontend-novoponto pull request #5
Opened 2023-01-16 15:05 UTC by AmandaFernandes0701

Horário obrigatório ocultado no menu de administração e página do usuário

2023-01-17 14:25 UTC, silliony requested changes
Curti a ideia que você teve de comentar para fora do código a funcionalidade da página, pórem a parte de sessões também foi removida da página de consulta de horas.

2023-01-17 14:25 UTC, silliony commented on src/styles/compiled/antdDark.css
> +  display: none;
Essa alteração ocasiona a ocultação de todos os elementos do ponto que utilizam essa classe. Recomendo comentar a parte do codigo que adiciona o elemento na página (como vc fez no restos do código), para evitar tal conflito.

2023-01-17 14:25 UTC, silliony requested changes
Curti a ideia que você teve de comentar para fora do código a funcionalidade da página, pórem a parte de sessões também foi removida da página de consulta de horas.

2023-01-18 14:23 UTC, joaopedropiraja reviewed
Bom demais!! Segundo parabéns do dia! kkkkkk

2023-01-18 14:23 UTC, merged